### ISSUE TITLE
If else statements breaks formatting

### ISSUE THREAD

**Issue by cwouter** [redfoos/logstash-intellij-plugin#10]
![image](https://user-images.githubusercontent.com/1439383/72014143-9ddcda00-325f-11ea-809a-2db72ca1c430.png)

Everything above the if/else statements gets aligned correctly. But after the if statement spaces are automatically removed. This issue might be related to #8.

**Comment by cwouter** [comment]
I can confirm it is related to #8. Once I replace the empty bracket things starting to work correctly.

**Comment by redfoos** [comment]
@cwouter, yes you right it was related issues. Fixed
