### ISSUE TITLE
not compatible with IntelliJ Ultimate 2020.1

### ISSUE THREAD

**Issue by vincent-fuchs** [redfoos/logstash-intellij-plugin#12]
Hi,

None of the latest versions seem to work with latest IntelliJ (I am using 2020.1 , Ultimate edition). I really find it super useful, I hope this can be fixed !

Thanks

--
Vincent

**Comment by edgonzales** [comment]
+1

**Comment by holive** [comment]
+1

**Comment by muklej** [comment]
+1

**Comment by pgilad** [comment]
Don't think these comment +1s are any good. I suggest someone get a stack trace or upgrade guide and starts working on a PR (or fork) to make the plugin 2020.1 compatible

**Comment by pgilad** [comment]
Ok so I took matters to my own hands 😆 and made a `2020.1` compatible version:
https://github.com/pgilad/logstash-intellij-plugin/releases/download/v0.6/logstash-intellij-plugin-0.6-2020.1.zip

See release here: https://github.com/pgilad/logstash-intellij-plugin/releases/tag/v0.6

If this works well for everyone, we should merge it to the main repo @redfoos

**Comment by vincent-fuchs** [comment]
> Ok so I took matters to my own hands 😆 and made a `2020.1` compatible version:
> https://github.com/pgilad/logstash-intellij-plugin/releases/download/v0.6/logstash-intellij-plugin-0.6-2020.1.zip
> 
> See release here: https://github.com/pgilad/logstash-intellij-plugin/releases/tag/v0.6
> 
> If this works well for everyone, we should merge it to the main repo @redfoos

Just installed it and it seems to be OK ! Thanks a lot !!

**Comment by redfoos** [comment]
Hello @pgilad, create pls merge request and i merge it.
Thanks a lot for your work!

**Comment by pgilad** [comment]
@redfoos https://github.com/redfoos/logstash-intellij-plugin/pull/13
