### ISSUE TITLE
Syntaxerror on REGEXPEQUAL

### ISSUE THREAD

**Issue by Hooddominator** [redfoos/logstash-intellij-plugin#14]
got syntaxerror on using REGEXPEQUAL as if-statement as shown in screenshot, but configuration works quite well in logstash...
![Bildschirmfoto vom 2020-04-24 14-49-39](https://user-images.githubusercontent.com/1444291/80215125-3c891d00-863c-11ea-8808-d834c377a207.png)

nice plugin btw !

**Comment by redfoos** [comment]
@Hooddominator, The problem is not actually in regexpequal, but that the array was previously handled incorrectly, now the problem has been fixed
