### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by datavistics** [redfoos/logstash-intellij-plugin#2]
There should be an ability to comment out code. For me this is not working.

**Comment by redfoos** [comment]
@datavistics. hello! Can you please give more complex explanation of your problem? 
This plugin support highlighting of comments: 
![image](https://user-images.githubusercontent.com/30526160/58779105-8361c480-85dd-11e9-8eec-c1dfcc4cc34d.png)
But if you mean auto comment and uncomment by Ctrl + / i try to add it in near update.

**Comment by redfoos** [comment]
@datavistics, i don't know what do you mean but i add auto comment in 0.4 release.

**Comment by datavistics** [comment]
Sorry for the delay I was on vacation :) 

Id like to be able to use Cmd+/ to comment out code.

But it seems you are adding this in the 0.4 release!

**Comment by datavistics** [comment]
Just tested this out, its great. Thanks so much!

**Comment by redfoos** [comment]
@datavistics, thank you too for your feedback!
