### ISSUE TITLE
Allow field names that include -

### ISSUE THREAD

**Issue by pgpx** [redfoos/logstash-intellij-plugin#3]
According to <https://www.elastic.co/guide/en/logstash/current/field-references-deepdive.html> field names should be allowed to contain anything except square brackets, but the plugin complains if a field name contains a hyphen.  For example:

```
if [http-element] in [ "rhead", "ihead" ] {
```

Gives the error: `, Logstash token type.IDENTIFIER, Logstash token type.[, Logstash token type.if, Logstash token type.{ or Logstash token type.} expected, got '['`

I couldn't see an obvious place to put a fix in the syntax files, and I'm only just starting to work with Logstash configs, so I'm not sure whether hyphens are generally discouraged in field names anyway.

**Comment by redfoos** [comment]
@pgpx, thank you for issue, i will fix it in next release

**Comment by redfoos** [comment]
@pgpx, [Fixed ](https://github.com/redfoos/logstash-intellij-plugin/releases/tag/releasebuild_0.5)
