### ISSUE TITLE
syntax error for field beginning with number

### ISSUE THREAD

**Issue by neu5ron** [redfoos/logstash-intellij-plugin#4]
I have a field named `[domain][1n2_name]`

logstash config gives syntax error highlighting, I assume because of the number -- because if I change it to say `[domain][one_name]`then it works fine.

again, thank you for this plugin and the fix for the last issue I submitted.
![Selection_001-1](https://user-images.githubusercontent.com/6351842/60558029-ad5df200-9d15-11e9-9ec1-325641417405.jpg)

**Comment by redfoos** [comment]
@neu5ron, thank you for your issue i will try to fix it in next release.

**Comment by redfoos** [comment]
@neu5ron, [Fixed ]https://github.com/redfoos/logstash-intellij-plugin/releases/tag/releasebuild_0.5)
