### ISSUE TITLE
Plugin 'logstash config support' is incompatible with this installation. (WebStorm 2019.3)

### ISSUE THREAD

**Issue by sbjovanovski** [redfoos/logstash-intellij-plugin#6]
After upgrading WebStorm to the latest version **2019.3** I keep getting this error and I don't have anymore **Syntax highlighting**, **Keyword completion**, **Brace matching** nor **Auto formatting**.

Is there any way to fix this?

**Comment by sbjovanovski** [comment]
I downgrade my WebStorm to 2019.2 and it seems to be working now. Please fix this to support version 2019.3

**Comment by zenonwch** [comment]
same for the Intellij IDEA v 2019.3

**Comment by redfoos** [comment]
Hello! Thank you for your issue i will fix it as soon as possible.

**Comment by redfoos** [comment]
@sbjovanovski, @zenonwch, [release_0.51](https://github.com/redfoos/logstash-intellij-plugin/releases/tag/releasebuild_0.51)

**Comment by sbjovanovski** [comment]
Sweet, works like a charm @redfoos . Thank you :)

**Comment by redfoos** [comment]
@sbjovanovski, pls star if it is not difficult for you :)

**Comment by zenonwch** [comment]
@redfoos Intellij IDEA 2019.3 doesn't see the new version (.
![image](https://user-images.githubusercontent.com/17174214/70320139-a4290200-182c-11ea-8115-d4dff268a2bd.png)

**Comment by redfoos** [comment]
@zenonwch, hello! JetBrains not yet approved the new version yet, but you can download it from GitHub and install manually: [readme.md](https://github.com/redfoos/logstash-intellij-plugin/blob/master/readme.md)

**Comment by zenonwch** [comment]
@redfoos hanks for the answer. Plugin works.
