### ISSUE TITLE
Comments breaks file formatting

### ISSUE THREAD

**Issue by ztyzbb** [redfoos/logstash-intellij-plugin#7]
![QQ截图20191225162333](https://user-images.githubusercontent.com/22043636/71439037-f2963600-2732-11ea-911f-5ed916b00515.png)
Comment line will always get a intend.
Especially when comment on first line in file, which breaks whole file's formatting.
Thank you!

**Comment by redfoos** [comment]
@ztyzbb, hello! Thank you for your issue, i will fix it as soon as possible!

**Comment by redfoos** [comment]
fixid
