### ISSUE TITLE
Syntax error on empty arrays

### ISSUE THREAD

**Issue by ugdpy** [redfoos/logstash-intellij-plugin#8]
Hello,

The plugin does not appear to support empty arrays `[]` and throw a syntax error. But the syntax is supported by logstash as we can see here [it is a default value](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-patterns_dir)

```
filter {
    grok {
        tag_on_failure => []
        match => {"message" => "toto"}
    }
}
```
This is a valid syntax but this flagged as an error.

This is a great plugin, keep up the good work.

**Comment by redfoos** [comment]
@ugdpy, Hello! Thank you for your issue, i will fix it as soon as possible!

**Comment by redfoos** [comment]
fixed
