### ISSUE TITLE
Writing regex with dots

### ISSUE THREAD

**Issue by ugdpy** [redfoos/logstash-intellij-plugin#9]
Hello

I found that typing a regex in an order or another does not show the same result, some will mark it as an error even when it's not. And if you copy, then paste the regex it is shown as correct syntax, example : 

![regex_syntax_check_example](https://user-images.githubusercontent.com/34677702/71623628-59599a80-2bde-11ea-8740-f18c7192d7d3.PNG)

I've typed the first part and then copied and pasted the second part.

Keep up the good work, this is a nice plugin.

**Comment by redfoos** [comment]
@ugdpy, thank you again!

**Comment by redfoos** [comment]
@ugdpy, now there are no beautiful way to fix this problem.
